### PR TITLE
#163351740 create,delete meetup and fix db error

### PR DESCRIPTION
**Pull request by bencyn**
## What does this PR do?

creates, gets and deletes a meetup record. Also fixes database instance error

## Description of tasks to be completed?

1. Write tests to test all endpoints
2. implement the post meetup endpoint
3. protect  private routes
4. write queries to add a meetup record in the database
5. write queries to validate if the user is an admin
6. implement delete meetup endpoint
7. write a query to delete a meetup record

## How should this be manually tested?
1. Create a virtual environment:
    `virtualenv -p python3 venv`

2.  Activate the virtual environment 
   `source venv/bin/activate`

3. Clone this repository 
    ` https://github.com/bencyn/Questioner.git`

4. cd into the folder 
    `  cd Questioner `

5. Switch to current branch
  ` git checkout ft-v2-create-delete-meetup-163351740`

6. Install requirements
   `pip install -r requirements.txt`

7. Export environment variables
    - `export SECRET_KEY ="random string here"`
    - `export APP_SETTINGS="development"`
    - `export DATABASE_URL="dbname='questioner' host='localhost' port='5432' user='postgres' password='<password>'"`
    - `export TEST_DATABASE_URL="dbname='test_question' host='localhost' port='5432' user='postgres' password='<password>'"`

8. run python run.py
   
## Pivotal tracker story associated with this PR:

https://www.pivotaltracker.com/story/show163351740

### Create a meetup record
image

### Get a specific meetup record
image

### Get all upcoming meetups
image

### Delete a meetup record
image

### CODE REVIEW

**Comment by Siffersari** [comment]
Good job

**Comment by emdeechege** [comment]
Your PR is fully packed, consider splitting the stories. Good job though!

**Comment by Ogutu-Brian** [comment]
Nice job @bencyn , you can consider making the story ids clickable instead of putting the whole url through this format `[#story-id](story-url)`

**Comment by a-braham** [comment]
Fine work right there, consider putting your environment variables in a .env file..

**Comment by Felix45** [comment]
Fine job.

**Pull request merged**
