### PR TITLE
#163223221 setup database 

### PR DESCRIPTION
**Pull request by bencyn**
## What does this PR do?

This pull request sets up a PostgreSQL database

## Description of tasks to be completed?

1.  Connect a test and live PostgreSQL database to the app
2. Define configurations and connection of both databases using psycopg2 **package**

## How should this be manually tested?
1. Create a virtual environment:
    `virtualenv -p python3 venv`

2.  Activate the virtual environment 
   `source venv/bin/activate`

3. Clone this repository 
    ` https://github.com/bencyn/Questioner.git`

4. cd into the folder 
    `  cd Questioner `

5. Switch to current branch
  ` git checkout ch-setup-database-16322322`

6. `pip install -r requirements.txt`

7. Export environment variables
    - `export SECRET_KEY ="random string here"`
    - `export APP_SETTINGS="development"`
    - `export DATABASE_URL="dbname='questioner' host='localhost' port='5432' user='postgres' password='<password>'"`
    - `export TEST_DATABASE_URL="dbname='test_question' host='localhost' port='5432' user='postgres' password='<password>'"`

8. run python run.py
   
## Pivotal tracker story associated with this PR:

https://www.pivotaltracker.com/story/show/163223221

### CODE REVIEW

**Comment by khwilo** [comment]
Your build error is because of this:
pkg-resources-error

When executing `pip freeze` use this command 
`pip freeze | grep -v "pkg-resources" > requirements.txt` to avoid adding the package **pkg-resources** to the requirements.txt file.

**Comment by emdeechege** [comment]
I highly doubt you should share your database credentials here. Let users who want to test create their own local databases.

**Comment by bencyn** [comment]
> I highly doubt you should share your database credentials here. Let users who want to test create their own local databases.

Thanks for the feedback. Already fixed

**Comment by bencyn** [comment]
> Your build error is because of this:
> pkg-resources-error
> 
> When executing `pip freeze` use this command
> `pip freeze | grep -v "pkg-resources" > requirements.txt` to avoid adding the package **pkg-resources** to the requirements.txt file.

**Comment by bencyn** [comment]
> > Your build error is because of this:
> > pkg-resources-error
> > When executing `pip freeze` use this command
> > `pip freeze | grep -v "pkg-resources" > requirements.txt` to avoid adding the package **pkg-resources** to the requirements.txt file.

Thanks

**Comment by dennisdnyce** [comment]
Also under related pivotal tracker story id header, you can add a link to the PT board for ease of access.

**Comment by bencyn** [comment]
> Also under related pivotal tracker story id header, you can add a link to the PT board for ease of access.

When you hover the #id it's a link by itself. Redirects you to pivotal board stories

**Pull request merged**
