### PR TITLE
#163300021 Ch implement user signup,login and authorization token

### PR DESCRIPTION
**Pull request by bencyn**
## What does this PR do?

allow a user to register, login, generate authorization token, get all users and get specific user by id.
## Description of tasks to be completed?

1. Write tests to test all endpoints
2. Generate jwt authorization token on signup and login
3. Write fetch queries in the user model to validate user login input
4. Write insert queries in the user model to record user register info
5. Write fetch queries to get al user records
6. Writer queries to get a specific user by id

## How should this be manually tested?
1. Create a virtual environment:
    `virtualenv -p python3 venv`

2.  Activate the virtual environment 
   `source venv/bin/activate`

3. Clone this repository 
    ` https://github.com/bencyn/Questioner.git`

4. cd into the folder 
    `  cd Questioner `

5. Switch to current branch
  ` git checkout ch-implement-userendpoints-163300021`

6. Install requirements
   `pip install -r requirements.txt`

7. Export environment variables
    - `export SECRET_KEY ="random string here"`
    - `export APP_SETTINGS="development"`
    - `export DATABASE_URL="dbname='questioner' host='localhost' port='5432' user='postgres' password='<password>'"`
    - `export TEST_DATABASE_URL="dbname='test_question' host='localhost' port='5432' user='postgres' password='<password>'"`

8. run python run.py
   
## Pivotal tracker story associated with this PR:

https://www.pivotaltracker.com/story/show/163300021

### User signup

screenshot from 2019-01-21 02-01-49

## User Login

image

### Get all users 

image

### Get a specific user

image

### CODE REVIEW

**Comment by MbuguaCaleb** [comment]
good job .!!

**Comment by dennisdnyce** [comment]
very impressive

**Comment by Felix45** [comment]
This looks good bro.

**Comment by dennisdnyce** [comment]
Looks great man

**Comment by SolomonMacharia** [comment]
Good job. :100:

**Pull request merged**
